server:
  name: webflux_test
  port: 8080
  address: 127.0.0.1
  servlet:
    context-path: /
  shutdown: graceful
spring:
  main:
    web-application-type: reactive
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  datasource:
    platform: h2
    url: r2dbc:h2:mem:///webflux;DB_CLOSE_DELAY=-1
    name: webflux
    username: sa
    password: